version: '3'

services:

  
  db:
  
    image: postgres:14-alpine3.19  

    container_name: postgres
    ports:
      - '9000:5432'
      
    environment:
      - 'POSTGRES_PASSWORD=1234567890'
      - 'POSTGRES_USER=postgres'

    volumes:
      - /home/vitass/Desktop/kanban valume/postgres:/var/lib/postgresql/data

 
  

  app:
    build:
      context: app/
      dockerfile: Dockerfile

    ports:
       - '8000:8000'

    volumes:
       -  /home/vitass/Desktop/kanban valume/app   

    command: python ./main.py


    # network_mode: host
    depends_on:
      - db


