version: '3'

services:

  
  db:
  
    image: postgres:14-alpine3.19  

    container_name: postgres
    ports:
      - '9000:5432'
      
    environment:
      - 'POSTGRES_PASSWORD=1234567890'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=postgres'

  test_db:
  
    image: postgres:14-alpine3.19  

    container_name: postgres_test
    ports:
      - '7000:5432'
      
    environment:
      - 'POSTGRES_PASSWORD=1234567890t'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=postgres '      

  src:
    build: .


    environment:
       - SQL_DATABASE_URL=postgresql+psycopg2://postgres:1234567890@db:9000/postgres
       - TEST_SQL_DATABASE_URL=postgresql+psycopg2://postgres_test:1234567890t@db_test:7000/postgres_test  

    ports:
       - '8000:8000'


    command: python ./main.py

    tty: true
    stdin_open: true

    depends_on:
      - db
      - test_db


