"""empty message

Revision ID: 7d59c0022b18
Revises: 77144fe7f918
Create Date: 2024-09-21 21:24:12.092400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d59c0022b18'
down_revision: Union[str, None] = '77144fe7f918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('others_u', 'others_users', ['user_id', 'board_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('others_u', 'others_users', type_='unique')
    # ### end Alembic commands ###
