version: '3'

services:

  
  db:
  
    image: postgres:14

    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_PASSWORD=1234567890'
      - 'POSTGRES_USER=postgres'
 
  

  app:
    build:
      context: app/
      dockerfile: Dockerfile

    ports:
      - '5432:5432'

    command: python ./models.py

    network_mode: host
    depends_on:
      - db


