version: '3'

services:

  
  server:
  
  
    build:
      context: server/
      dockerfile: Dockerfile

    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_PASSWORD=1234567890'
      - 'POSTGRES_USER=postgres'
    image: postgres:14 
  

  client:
    build:
      context: client/
      dockerfile: Dockerfile

    ports:
      - '5432:5432'

    command: python ./models.py

    network_mode: host
    depends_on:
      - server


